### PR TITLE
[c_hybrid_mpi+openmp_dir] Allow setting CFLAGS

### PR DESCRIPTION
**Pull request by giordano**
Also, default optimisation level to `-O3`.

### CODE REVIEW

**Comment by ikirker** [comment]
Why?

**Comment by giordano** [comment]
What "why" specifically?  `CFLAGS` is [already used in several places](https://github.com/search?q=repo%3AUCL-RITS%2Fpi_examples+CFLAGS&type=code), as is [`-O3`](https://github.com/search?q=repo%3AUCL-RITS%2Fpi_examples%20-O3&type=code).  On Nvidia Grace I get 50-75% better performance by setting `CFLAGS=-O3`  (even better with `-O3 -march=native`), compared to current setup, which doesn't let passing arguments from the command line at all.

**Comment by ikirker** [comment]
I guess I see the utility of adding `CFLAGS`, so the "why" is aimed at the value of adding in performance-tweaking to a toy example program using an option that [apparently still occasionally breaks things](https://github.com/UCL-RITS/pi_examples/blob/fc92267c33b8ffb0e51e55083c71d5fb9926bfac/fortran_omp_pi_dir/Makefile.intel#L5).

Technically it's fine.

**Comment by giordano** [comment]
Ok, I don't mind demoting the default to `-O2` or even just remove the default, if that's the issue, but I'd still like to be able to set flags from the command line without having to edit the makefile.

**Comment by ikirker** [comment]
It's really more that if someone is caring a lot about the absolute performance of these things, then something has gone awry, because -- at least for the ones I wrote -- they were never really intended to be anything other than language, framework/method, and basic scaling demos.

But it's fine, I don't mind merging it.

**Pull request merged**
